apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deploy
  labels:
    app: frontend-app
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app-container
        image: "docker.io/swethap99/frontend:latest"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80